### ISSUE TITLE
Create the design for buttons on the site

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#117]
Create the design for buttons on the site
This will help the site feel uniform and consistent
The buttons are for voting
Do not worry about the ADMIN interface  - the regular user is the most important one at this point

**Comment by rrocchio** [comment]
![screen shot 2015-07-24 at 9 34 09 am](https://cloud.githubusercontent.com/assets/718820/8879588/3ac2c2b8-31e7-11e5-8064-48c1c56cd201.png)

**Comment by rrocchio** [comment]
@laurencullen  - one thing to note - is that the voting panel comes up when you look at the detail of an idea or a project:
![screen shot 2015-07-24 at 9 47 57 am](https://cloud.githubusercontent.com/assets/718820/8879840/1e5681da-31e9-11e5-9ca9-49db627569e0.png)

**Comment by laurencullen** [comment]
Here are some png buttons. Please let me know if you need any changes or anything else.
![ucnext buttons-01](https://cloud.githubusercontent.com/assets/13141571/8917535/66f5be9e-3467-11e5-8859-ec6b643b384d.png)
![ucnext buttons-02](https://cloud.githubusercontent.com/assets/13141571/8917536/6708ec6c-3467-11e5-928b-8b734ead4b05.png)
![ucnext buttons-03](https://cloud.githubusercontent.com/assets/13141571/8917538/670b85c6-3467-11e5-85dc-cc2b5ab3de3f.png)
![ucnext buttons-04](https://cloud.githubusercontent.com/assets/13141571/8917537/670b14d8-3467-11e5-9e3d-3a1bed417f84.png)
![ucnext buttons-05](https://cloud.githubusercontent.com/assets/13141571/8917539/670c0f82-3467-11e5-9614-166e619ad5cf.png)
![ucnext buttons-06](https://cloud.githubusercontent.com/assets/13141571/8917542/6710f402-3467-11e5-9a12-0156185379cd.png)
![ucnext buttons-07](https://cloud.githubusercontent.com/assets/13141571/8917541/670f5c8c-3467-11e5-9d45-8870b990fbfb.png)

**Comment by pmeads** [comment]
Hi Lauren,

There are a couple more buttons we'll need:
Withdraw Participation
Withdraw Support

Thanks!

**Comment by pmeads** [comment]
Also, the buttons should be highlighted on rollover - so we need rollover images as well

**Comment by laurencullen** [comment]
Here are the buttons including rollover ones (colors made to be accessible). The size changed, so posting all of them. Please let me know any revisions or if you need anything else.

![edit](https://cloud.githubusercontent.com/assets/13141571/8919883/10da037e-3478-11e5-870f-d8b4cd2092ed.png)
![i-think-this-is-a-good-idea](https://cloud.githubusercontent.com/assets/13141571/8919882/10d84d36-3478-11e5-954b-a84a1a4f7e95.png)
![i-want-to-learn-more](https://cloud.githubusercontent.com/assets/13141571/8919887/10dc5cd2-3478-11e5-8e00-8fc569f48023.png)
![i-would-participate](https://cloud.githubusercontent.com/assets/13141571/8919886/10db7006-3478-11e5-9784-878b64dbc674.png)
![manage-documents](https://cloud.githubusercontent.com/assets/13141571/8919885/10db1480-3478-11e5-82b7-165f13ec135f.png)
![withdraw-participation](https://cloud.githubusercontent.com/assets/13141571/8919884/10da7be2-3478-11e5-937f-430623bee60b.png)
![withdraw-support](https://cloud.githubusercontent.com/assets/13141571/8919888/10e7e6ce-3478-11e5-8591-483becc10cb9.png)
![would-participate](https://cloud.githubusercontent.com/assets/13141571/8919889/10e9e8f2-3478-11e5-9aaf-59667bebb662.png)
![good-project](https://cloud.githubusercontent.com/assets/13141571/8919891/10edbc98-3478-11e5-8284-29d9f93366d1.png)
![edit-rollover](https://cloud.githubusercontent.com/assets/13141571/8919890/10ecc054-3478-11e5-8cc7-7e835962440f.png)
![good-project-rollover](https://cloud.githubusercontent.com/assets/13141571/8919892/10ededb2-3478-11e5-81d6-182512a9befd.png)
![i-think-rollover](https://cloud.githubusercontent.com/assets/13141571/8919893/10ee214c-3478-11e5-9cea-8048eb7f9dea.png)
![i-want-to-rollover](https://cloud.githubusercontent.com/assets/13141571/8919894/10fa5b60-3478-11e5-882b-fed2f9c83c59.png)
![i-would-rollover](https://cloud.githubusercontent.com/assets/13141571/8919895/10fc0ed8-3478-11e5-8f10-f25c440af96a.png)
![manage-documents-rollover](https://cloud.githubusercontent.com/assets/13141571/8919897/10fe952c-3478-11e5-9bc7-11385064224d.png)
![withdraw-participation-rollover](https://cloud.githubusercontent.com/assets/13141571/8919899/110146be-3478-11e5-8495-63575f416fcf.png)
![withdraw-support-rollover](https://cloud.githubusercontent.com/assets/13141571/8919898/10ff82b6-3478-11e5-9b96-532b6b391aef.png)
![would-participate-rollover](https://cloud.githubusercontent.com/assets/13141571/8919896/10fcae88-3478-11e5-9bb6-05ba682e9337.png)

**Comment by ctmcintyre** [comment]
I like the lighter colors in general. 

The green, blue, brown feel a bit like summer camp colors.  Not that
they are bad, it's just where I go when I see those colors together. 
Perhaps we could go lighter and more "surf" colors to coordinate with
the wave motif.  The seafoam, sky blue and sunlight colors of the
rollover buttons fit well.

IMO, it would be great if those were the default colors.

C
> laurencullen <mailto:notifications@github.com>
> July 27, 2015 at 4:00 PM
>
> Here are the buttons including rollover ones (colors made to be
> accessible). The size changed, so posting all of them. Please let me
> know any revisions or if you need anything else.
>
> edit
> <https://cloud.githubusercontent.com/assets/13141571/8919883/10da037e-3478-11e5-870f-d8b4cd2092ed.png>
> i-think-this-is-a-good-idea
> <https://cloud.githubusercontent.com/assets/13141571/8919882/10d84d36-3478-11e5-954b-a84a1a4f7e95.png>
> i-want-to-learn-more
> <https://cloud.githubusercontent.com/assets/13141571/8919887/10dc5cd2-3478-11e5-8e00-8fc569f48023.png>
> i-would-participate
> <https://cloud.githubusercontent.com/assets/13141571/8919886/10db7006-3478-11e5-9784-878b64dbc674.png>
> manage-documents
> <https://cloud.githubusercontent.com/assets/13141571/8919885/10db1480-3478-11e5-82b7-165f13ec135f.png>
> withdraw-participation
> <https://cloud.githubusercontent.com/assets/13141571/8919884/10da7be2-3478-11e5-937f-430623bee60b.png>
> withdraw-support
> <https://cloud.githubusercontent.com/assets/13141571/8919888/10e7e6ce-3478-11e5-8591-483becc10cb9.png>
> would-participate
> <https://cloud.githubusercontent.com/assets/13141571/8919889/10e9e8f2-3478-11e5-9aaf-59667bebb662.png>
> good-project
> <https://cloud.githubusercontent.com/assets/13141571/8919891/10edbc98-3478-11e5-8284-29d9f93366d1.png>
> edit-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919890/10ecc054-3478-11e5-8cc7-7e835962440f.png>
> good-project-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919892/10ededb2-3478-11e5-81d6-182512a9befd.png>
> i-think-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919893/10ee214c-3478-11e5-9cea-8048eb7f9dea.png>
> i-want-to-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919894/10fa5b60-3478-11e5-882b-fed2f9c83c59.png>
> i-would-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919895/10fc0ed8-3478-11e5-8f10-f25c440af96a.png>
> manage-documents-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919897/10fe952c-3478-11e5-9bc7-11385064224d.png>
> withdraw-participation-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919899/110146be-3478-11e5-8495-63575f416fcf.png>
> withdraw-support-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919898/10ff82b6-3478-11e5-9b96-532b6b391aef.png>
> would-participate-rollover
> <https://cloud.githubusercontent.com/assets/13141571/8919896/10fcae88-3478-11e5-9bb6-05ba682e9337.png>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/117#issuecomment-125374183>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by krozett** [comment]
I don't have any strong feelings about the colors, but... just to throw my 2 cents in, we should be using CSS-styled text rather than images. There are 3 reasons:
1) for SEO and accessibility: crawlers and screen readers can't read text embedded into images.
2) if our colors or design ever changes, we can make a simple CSS change rather than upload a whole new set of images.
3) better user experience: images take some time to load, text is near-instant

All we need to implement the buttons in CSS are the hex colors that were used (background color for button, font color, border color, drop-shadow color).

**Comment by laurencullen** [comment]
Yes, the buttons could be implemented in CSS - just specifying border-radius, border color, color, drop-shadow, etc. I can provide any details once these proofs are finalized.

Here are new options for colors. The default state is now the lighter version. I'm also working with color accessibility (for example yellow/orange and white text can't be used together, so I made the hover deeper towards red instead of brown).

Please let me know any feedback.

Thanks!
![edit-hover](https://cloud.githubusercontent.com/assets/13141571/8944008/e5d3115a-3532-11e5-8a2f-542e3c087117.png)
![edit](https://cloud.githubusercontent.com/assets/13141571/8944009/e5e50cca-3532-11e5-9f11-ddb1bbd00e28.png)
![good-project-hover](https://cloud.githubusercontent.com/assets/13141571/8944010/e5ea6b98-3532-11e5-820a-39cbdbada87d.png)
![good-project](https://cloud.githubusercontent.com/assets/13141571/8944011/e5eca66a-3532-11e5-8099-e95de11ad326.png)
![i-think-hover](https://cloud.githubusercontent.com/assets/13141571/8944012/e5ec94cc-3532-11e5-8f86-9c61ee5ec597.png)
![i-think](https://cloud.githubusercontent.com/assets/13141571/8944013/e5eef2d0-3532-11e5-82da-3e274a963ceb.png)
![i-want-hover](https://cloud.githubusercontent.com/assets/13141571/8944014/e5efc502-3532-11e5-9c39-12ea77c23a74.png)
![i-want](https://cloud.githubusercontent.com/assets/13141571/8944015/e5f89e34-3532-11e5-9a8d-dad42ec69811.png)
![i-would-hover](https://cloud.githubusercontent.com/assets/13141571/8944017/e5fee12c-3532-11e5-8be7-0aee8bbc3479.png)
![i-would](https://cloud.githubusercontent.com/assets/13141571/8944016/e5fd4e66-3532-11e5-8777-16365e35d826.png)
![manage-hover](https://cloud.githubusercontent.com/assets/13141571/8944018/e600c7da-3532-11e5-91b8-eef904c767f1.png)
![manage](https://cloud.githubusercontent.com/assets/13141571/8944020/e6033196-3532-11e5-98bb-2d6f210d175b.png)
![withdraw-participation-hover](https://cloud.githubusercontent.com/assets/13141571/8944019/e60313aa-3532-11e5-9272-f3e0bcfa3414.png)
![withdraw-participation](https://cloud.githubusercontent.com/assets/13141571/8944021/e60fe238-3532-11e5-997c-f4399fd2b3ce.png)
![withdraw-support-hover](https://cloud.githubusercontent.com/assets/13141571/8944022/e6114f9c-3532-11e5-86ae-1053026780c9.png)
![withdraw-support](https://cloud.githubusercontent.com/assets/13141571/8944023/e6125f68-3532-11e5-93b6-40b01d8db003.png)
![would-participate-hover](https://cloud.githubusercontent.com/assets/13141571/8944024/e6146bd2-3532-11e5-9c0a-be6f8a286585.png)
![would-participate](https://cloud.githubusercontent.com/assets/13141571/8944025/e617e03c-3532-11e5-9b04-7f452bb8fb00.png)

**Comment by ctmcintyre** [comment]
Me likey!!!

> laurencullen <mailto:notifications@github.com>
> July 28, 2015 at 2:15 PM
>
> Yes, the buttons could be implemented in CSS - just specifying
> border-radius, border color, color, drop-shadow, etc. I can provide
> any details once these proofs are finalized.
>
> Here are new options for colors. The default state is now the lighter
> version. I'm also working with color accessibility (for example
> yellow/orange and white text can't be used together, so I made the
> hover deeper towards red instead of brown).
>
> Please let me know any feedback.
>
> Thanks!
> edit-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944008/e5d3115a-3532-11e5-8a2f-542e3c087117.png>
> edit
> <https://cloud.githubusercontent.com/assets/13141571/8944009/e5e50cca-3532-11e5-9f11-ddb1bbd00e28.png>
> good-project-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944010/e5ea6b98-3532-11e5-820a-39cbdbada87d.png>
> good-project
> <https://cloud.githubusercontent.com/assets/13141571/8944011/e5eca66a-3532-11e5-8099-e95de11ad326.png>
> i-think-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944012/e5ec94cc-3532-11e5-8f86-9c61ee5ec597.png>
> i-think
> <https://cloud.githubusercontent.com/assets/13141571/8944013/e5eef2d0-3532-11e5-82da-3e274a963ceb.png>
> i-want-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944014/e5efc502-3532-11e5-9c39-12ea77c23a74.png>
> i-want
> <https://cloud.githubusercontent.com/assets/13141571/8944015/e5f89e34-3532-11e5-9a8d-dad42ec69811.png>
> i-would-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944017/e5fee12c-3532-11e5-8be7-0aee8bbc3479.png>
> i-would
> <https://cloud.githubusercontent.com/assets/13141571/8944016/e5fd4e66-3532-11e5-8777-16365e35d826.png>
> manage-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944018/e600c7da-3532-11e5-91b8-eef904c767f1.png>
> manage
> <https://cloud.githubusercontent.com/assets/13141571/8944020/e6033196-3532-11e5-98bb-2d6f210d175b.png>
> withdraw-participation-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944019/e60313aa-3532-11e5-9272-f3e0bcfa3414.png>
> withdraw-participation
> <https://cloud.githubusercontent.com/assets/13141571/8944021/e60fe238-3532-11e5-997c-f4399fd2b3ce.png>
> withdraw-support-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944022/e6114f9c-3532-11e5-86ae-1053026780c9.png>
> withdraw-support
> <https://cloud.githubusercontent.com/assets/13141571/8944023/e6125f68-3532-11e5-93b6-40b01d8db003.png>
> would-participate-hover
> <https://cloud.githubusercontent.com/assets/13141571/8944024/e6146bd2-3532-11e5-9c0a-be6f8a286585.png>
> would-participate
> <https://cloud.githubusercontent.com/assets/13141571/8944025/e617e03c-3532-11e5-9b04-7f452bb8fb00.png>
>
> ---
> Reply to this email directly or view it on GitHub
> <https://github.com/universityofcalifornia/NeXt/issues/117#issuecomment-125755970>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services
University of California Santa Cruz

office: 831/459-5746
mobile: 831/239-5839

**Comment by krozett** [comment]
@laurencullen - okay, glad we're on the same page about the CSS. :+1: 

We also will need 'delete' buttons at some point. That's an admin interface thing, though, and not as urgent.

Also I was wondering why some of the buttons are ALL CAPS and others are mixed case? I think it would be better to be consistent. Another alternative would be to shorten the long buttons so they could be all caps too, for example: "GOOD IDEA", "LEARN MORE", etc.

**Comment by laurencullen** [comment]
@krozett - yes, sounds good about consistency. I think shortening the long buttons so that they are all caps too works good. If you prefer the long buttons and everything mixed case, please let me know because I will do that instead.

Here are the new shorter buttons and the delete button (default states are the lighter ones with blue text and hover states are the darker ones with white text):
![delete hover](https://cloud.githubusercontent.com/assets/13141571/8988927/d8a366e4-369d-11e5-9766-4f79a18c7023.png)
![delete](https://cloud.githubusercontent.com/assets/13141571/8988928/d8b4beb2-369d-11e5-930c-9b3afbe96aa8.png)
![good idea hover](https://cloud.githubusercontent.com/assets/13141571/8988929/d8bce8a8-369d-11e5-929d-a1eeaf45147c.png)
![good idea](https://cloud.githubusercontent.com/assets/13141571/8988932/d8c00286-369d-11e5-8664-1ef570a8dfa2.png)
![learn more hover](https://cloud.githubusercontent.com/assets/13141571/8988931/d8bdd704-369d-11e5-9dc1-94fa7a762b0f.png)
![learn more](https://cloud.githubusercontent.com/assets/13141571/8988930/d8bdbd96-369d-11e5-8360-d7cdfb365a6b.png)
![would participate hover](https://cloud.githubusercontent.com/assets/13141571/8988933/d8c003f8-369d-11e5-822b-40d892626dfa.png)
![would participate](https://cloud.githubusercontent.com/assets/13141571/8988934/d8c68494-369d-11e5-9176-e470d2da082e.png)

**Comment by laurencullen** [comment]
Here is the CSS for all of the buttons. Please let me know if you need anything else. Thanks!

.button {
	border: 1px solid;
	border-radius: 5px;
	width: 210px;
	height: 40px;
	color: #1d4a86;
	text-shadow: 1px 1px 0px #999999;
}

a:hover {
	color: #ffffff;
	text-shadow: 1px 1px 0px #999999;
}

.goodProject {
	background: #c6e7c6;
	border: #5cb85c;
}

a:hover .goodProject {
	background: #5cb85c;
	border: #2e692e;
}

.wouldParticipate {
	background: #fff48b;
	border: #fdba35;
}

a:hover .wouldParticipate {
	background: #bb3200;
	border: #6a1c00;
}

.edit {
	background: #ccdded;
	border: #2d6892;
}

a:hover .edit {
	background: #3a71a5;
	border: #2d6892;
}

.manageDocuments {
	background: #39c7ff;
	border: #347bad;
}

a:hover .manageDocuments {
	background: #1d4a86;
	border: #347bad;
}

.goodIdea {
	background: #c6e7c6;
	border: #5cb85c;
}

a:hover .goodIdea {
	background: #5cb85c;
	border: #2e692e;
}

.learnMore {
	background: #39c7ff;
	border: #347bad;
}

a:hover .learnMore {
	background: #1d4a86;
	border: #347bad;
}

.delete {
	background: #ffafaf;
	border: #b36969;
}

a:hover .delete {
	background: #730000;
	border: #990000;
}

.withdrawParticipation {
	background: #c3bbb8;
	border: #5f5651;
}

a:hover .withdrawParticipation {
	background: #706660;
	border: #5f5651;
}

.withdrawSupport {
	background: #bac1bc;
	border: #454d47;
}

a:hover .withdrawSupport {
	background: #6a756c;
	border: #454d47;
}

**Comment by krozett** [comment]
Thanks Lauren!

To devs: use `btn` classes for different button colors now. We have these:
* `btn-edit`
* `btn-delete`
* `btn-support`
* `btn-participate`
* `btn-learn-more`
* `btn-withdraw-support`
* `btn-withdraw-participation`
* `btn-manage-documents`

Please use these or `btn-primary`, but you should refrain from using the others unless they show up in Lauren's design.

It's very easy to create a new button style. Use CSS like this:
```scss
.btn-example {
  @include button-variant      ($btn-default-color, background-color, border-color);
  @include button-variant-hover($btn-hover-color,   hover-background-color, hover-border-color);
}
```

background-color, border-color, hover-background-color, and hover-border-color should be replaced with the colors you want. You can leave `$btn-default-color` and `$btn-hover-color` as-is, those are the text colors, which are the same for all buttons. However you can use different ones.

**Comment by joshuaselsky** [comment]
* there are possible commits in the past that could partially close this
* we should audit the buttons site-wide to make sure the styling is correct

**Comment by krozett** [comment]
Button style audit should still happen. On some pages (group details page as admin) I think it looks bad having several wide buttons stacked horizontally.

I also modified the drop-shadow to be consistent with the text in yellow bubbles:
`0.77px 0.77px 0px rgba(153, 153, 153, 0.75);`

**Comment by joshuaselsky** [comment]
@krozett please fix the +1 button in the projects and ideas tables.

**Comment by ctrance** [comment]
@krozett @joshuaselsky - The "Would Participate" button is not showing the new colors, if the user has supported the idea already. Please see below.
![img_0740 1](https://cloud.githubusercontent.com/assets/1034174/13541972/8a830398-e214-11e5-875f-7b02453b34f8.PNG)

**Comment by ctrance** [comment]
@joshuaselsky @krozett - Where can I see "I think this is a good idea" button? I don't see it on Ideas list or details page?

**Comment by ctrance** [comment]
@krozett @joshuaselsky - "Delete" button on Events and People don't have the new color yet, see below:
![capture](https://cloud.githubusercontent.com/assets/1034174/13575857/d0c77b9a-e43f-11e5-9198-76b1f51ee49a.PNG)

**Comment by krozett** [comment]
@ctrance The 3 buttons you referred to have had their text changed. They are now these buttons: https://github.com/universityofcalifornia/NeXt/issues/117#issuecomment-126394985

**Comment by ctrance** [comment]
@krozett - Thanks for clarifying! I only have these issues  >> https://github.com/universityofcalifornia/NeXt/issues/117#issuecomment-192497606 and https://github.com/universityofcalifornia/NeXt/issues/117#issuecomment-193336377

**Comment by ctrance** [comment]
@krozett - I still see a green "Would Participate" button, instead of a the new color (light yellow). To replicate select "Good Idea" button first then open the vote pop up again and you'll see a green "Would Participate" button

**Comment by krozett** [comment]
@ctrance You may need to clear your cache. I checked it on staging and it appears to be working fine.

**Comment by ctrance** [comment]
@krozett - I made sure I cleared my cache this time :). 
- "Would Participate" button is now fixed on the vote pop up but not on the Idea details page, after supporting (click Good Idea) open the details of the Idea and you'll see green "Would Participate" button. 
- "Edit" button on People > Profile page still shows green.

**Comment by krozett** [comment]
@ctrance can you please test these things again?

**Comment by ctrance** [comment]
fixed
