### ISSUE TITLE
The UC Next Profile Page - should allow the USER To choose their Security Setting

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#133]
The Not logged in version of the People page - should just say "Please login" as a pop-up....

We need to add a field to the Logged in version of the UC Next Profile Page that lets the user select how public to make their Profile:

So the values should be:

1) HIDDEN ( which means no one but the USER can see their Profile - and it should say "Hidden" across the top)

2) PUBLISH TO UC NEXT users ( which means that only logged in Users can see their profile)

**Comment by joshuaselsky** [comment]
For any user profile information such as badges, those items should also respect the visibility settings of the user's profile.

**Comment by ctrance** [comment]
@joshuaselsky @krozett - User who sets their profile to "Hidden" don't see their name on "People" list, is that the expected behavior? I thought only they can see their profile if they set it to Hidden.

Also, if the hidden profile name is clicked from Badge, Group, Project, and Idea the app does not show any message I just get thrown to the home page. Maybe we show a pop up message informing the user that the clicked profile is hidden then do not go away from the current page?

**Comment by joshuaselsky** [comment]
Instead of hiding the user from the people list, we will show only their name and it will not be a hyperlink and anywhere else in the app where the user appears the name will also not be a link.

**Comment by krozett** [comment]
Just had a brain wave. When we are making users non-hyperlinks because of the privacy setting, I can add hover text to the name explaining why it is hidden. I think this is more useful as some users may be confused as to why some users' names are not clickable.

**Comment by ctrance** [comment]
fixed
