### ISSUE TITLE
On the home page of UC Next - changes when the User has logged in

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#138]
On the homepage of UC Next - lets add the following changes once the user has logged in:

1) The Login area, should go away and there should be a "Welcome "username" and a Logout Link"

**Comment by laurencullen** [comment]
Here is a proof with these changes to the header. Please let me know if you need any revises.

![ucnext new header-01](https://cloud.githubusercontent.com/assets/13141571/9208850/c4f73ca8-4028-11e5-9385-d4802fa55b24.jpg)

**Comment by laurencullen** [comment]
@rrocchio and @krozett  here is the new header from the other day. I just made some changes and will upload here and on the new ticket.
![ucnext header login](https://cloud.githubusercontent.com/assets/13141571/9278140/89f8ec90-4263-11e5-9d9e-1bc22ee707e9.jpg)
![ucnext logged in header-01](https://cloud.githubusercontent.com/assets/13141571/9278143/8d4e4fca-4263-11e5-9919-ba4c6793a513.jpg)
![ucnext logged in header-02](https://cloud.githubusercontent.com/assets/13141571/9278148/92569400-4263-11e5-9d70-6fd6bea978f2.jpg)

**Comment by laurencullen** [comment]
These attached new proofs might work best because button doesn't make sense given logout option in my account.

![ucnext header-04](https://cloud.githubusercontent.com/assets/13141571/9278603/b41cf6b2-4266-11e5-8696-433852086488.jpg)
![ucnext header-05](https://cloud.githubusercontent.com/assets/13141571/9278604/b422099a-4266-11e5-81a3-58fdf9fe6577.jpg)
