### ISSUE TITLE
Design the UC Next App Icon - for Saving the URL to a mobile dashboard

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#161]
@laurencullen  - Please design the App Icon for UC Next - this is so when we are on a mobile device, we can save it as a an app, for example on UCLA Mobile.

**Comment by laurencullen** [comment]
please see thread #162 https://github.com/universityofcalifornia/NeXt/issues/162

these design options were posted there:
![ucnexticon-01](https://cloud.githubusercontent.com/assets/13141571/9178864/cb31bde0-3f4d-11e5-9355-497a8c73f870.png)
![ucnexticon-02](https://cloud.githubusercontent.com/assets/13141571/9178866/cb33dc92-3f4d-11e5-8fa9-f23bcb136039.png)
![ucnexticon-03](https://cloud.githubusercontent.com/assets/13141571/9178865/cb32bbaa-3f4d-11e5-9c7e-8cc36698ee6f.png)
![ucnexticon-04](https://cloud.githubusercontent.com/assets/13141571/9178867/cb343e58-3f4d-11e5-9573-476245e871a3.png)
![ucnexticon-05](https://cloud.githubusercontent.com/assets/13141571/9178868/cb364db0-3f4d-11e5-9627-0e2b15f09809.png)

**Comment by rrocchio** [comment]
@laurencullen  - THESE ROCK !!!!
@ebollens  - good news - Lauren already created the UC NEXT App button
@ctmcintyre  - which one do you like best?  I like #'s 2, 3 and 5 - However - maybe 1 is best, since it will Say UC Next underneath it?

**Comment by ebollens** [comment]
I'm going to go with Option 1. 

The reasoning...

* Options 3 and 4 have a lot of text. Because of the size of the app icons on the home screen, that much text will get drowned out and not be visible. This is affirmed by the fact that 0 out of 40 apps (unless you count the numbers on the Clock app) have more than 8 different words on them (the most probably being Newsstand with 4).
* Options 2 and 5 show the title that is also shown when the app is saved. This makes it a bit redundant. While we could go with it, I'd point out that, on my phone, those that have an actual word in their icon are probably about 1 in 8.

**Comment by ctmcintyre** [comment]
Works for me!


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile
