### ISSUE TITLE
Stack the login above the search in the Header

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#204]

**Comment by laurencullen** [comment]
@krozett and @rrocchio here are the new headers. Please let me know any revisions. Do you prefer the login/logout as a button or just as a link as it currently is on the site?

![ucnext header login](https://cloud.githubusercontent.com/assets/13141571/9278163/c4777de6-4263-11e5-878a-080fedf91f1a.jpg)
![ucnext logged in header-01](https://cloud.githubusercontent.com/assets/13141571/9278164/c8a23654-4263-11e5-8673-cb25ace3e293.jpg)
![ucnext logged in header-02](https://cloud.githubusercontent.com/assets/13141571/9278169/cd4a4dae-4263-11e5-80ff-9b733953b094.jpg)

**Comment by laurencullen** [comment]
This was originally in #138

**Comment by laurencullen** [comment]
These attached new proofs make more sense than previous ones because button isn't necessary given that logout is an option under my account

![ucnext header-04](https://cloud.githubusercontent.com/assets/13141571/9278578/9415995a-4266-11e5-9c75-f9ed9b0e188e.jpg)
![ucnext header-05](https://cloud.githubusercontent.com/assets/13141571/9278579/9416a25a-4266-11e5-8170-70368d197794.jpg)

**Comment by ctrance** [comment]
fixed
