### ISSUE TITLE
When the user clicks "Contact" please open an email with ucnext@ucsc.edu

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#216]
@ebollens  - any chance you can slide this one in... we discussed it but never created a ticket for it, so it has gotten overlooked....

**Comment by rrocchio** [comment]
@ctmcintyre  - you created the email account called ucnext@ucsc.edu - for us to use with this link correct?

**Comment by ctmcintyre** [comment]
ucnext@ucsc.edu is an email account that the platform can send and receive from. I advise that we use that for systemic email use on the platform. 

ucnextsupport@ucsc.edu is a group list that many of us are in that I advise we use for the Contact form.  We will all receive email sent to this group. 

Just to be redundant, please use ucnextsupport@ucsc.edu for the contact page/form. 


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile

**Comment by ctmcintyre** [comment]
If we've got the cycles, it'd be great to make a contact form instead of a mailto, but we can always add this later. 


-- 

Charles McIntyre
Manager, Infrastructure & Operations

Applications & Project Management
Information Technology Services
University of California, Santa Cruz

831/459-5746 phone
831/239-5839 mobile

**Comment by ctmcintyre** [comment]
Can we make sure the Contact link has a mailto: to ucnextsupport@ucsc.edu

**Comment by ctrance** [comment]
fixed
