### ISSUE TITLE
Create a way for Local Logins to reset their passwords

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#223]
Create a way for Local Logins to reset their passwords

**Comment by krozett** [comment]
We will need an email sending system in place first.

**Comment by loganfranken** [comment]
:+1: (I could really use this right now, actually)

**Comment by shaun965** [comment]
For this feature, there will be a "forgotten password" link in the local login area and also a "reset password" link in the user panel. The "forgotten password" will direct the user to a form where they can enter their email and get a link to a form on the site where they can enter a new password. Once they enter the new password, they will be redirected to the login page where they can login with the new password. The "reset password" should go directly to the form. In the case they are already logged in to their account, they will have to retype their current password.

Because we added in password validation (at least 8 digit and contain at least one number and one character). It might be nice for users who are already registered with invalid passwords to get automatically directed to the reset password page upon log in so they can update their password to a valid password.

**Comment by joshuaselsky** [comment]
Here is a list of remaining to-dos for this issue.

* Rename password_resets to password_reset
* If the user successful uses the reset token, delete the value from the column.
* If the user clicks the reset password link and there is no token, redirect the user to the forgot password page.
* If the user tries to create a new reset token but they already have an unexpired token, do not replace the unexpired token.
* For the password reset email, the body should be:
  * We received a request to reset your password. You can ignore this message and your password will not be changed. If you do not change your password within two hours, the link will expire. Thanks for using UC NeXt!
* Make sure the error message shows when the user is redirected to the forgot password screen when they follow an expired reset link.

**Comment by ctrance** [comment]
@joshuaselsky - the reset email body has different message from the last comment https://github.com/universityofcalifornia/NeXt/issues/223#issuecomment-163042288

"We received a request to reset your password. Please use the reset password link below.
Reset password link 
If you ignore this message, your password will not be changed. After two hours, the link will automatically expire.
Thanks for using UC NeXt!"

**Comment by ctrance** [comment]
@joshuaselsky - I also got error page when I click the reset password link from the email, see below:
![capture](https://cloud.githubusercontent.com/assets/1034174/11791381/a51ff156-a255-11e5-8483-846621b1763e.PNG)

**Comment by shaun965** [comment]
I think Keith helped fix this issue just now by changing the default base URL. I tried just now and its working fine.

**Comment by ctrance** [comment]
Working good now, the only thing to fix is changing the reset password email message that @joshuaselsky mentioned in https://github.com/universityofcalifornia/NeXt/issues/223#issuecomment-163042288

**Comment by joshuaselsky** [comment]
Underneath the message text, we still need to include the reset link! 

Here's the full text with a fake link.

We received a request to reset your password. You can ignore this message and your password will not be changed. If you do not change your password within two hours, the link will expire. Thanks for using UC NeXt!

[Please click here to reset your password.](http://www.example.com)

**Comment by ctrance** [comment]
Fixed
