### ISSUE TITLE
Make Title required on all UC Next Components

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#228]
- projects
 - ideas
 - groups
 - events
- name - for people...

**Comment by ctrance** [comment]
Will test once I can log in to test site

**Comment by ctrance** [comment]
@shaun965 and @joshuaselsky - On events page, the validation error message appears as a tool tip on the Name field unlike other pages where there's a red text error on top of the form.

**Comment by shaun965** [comment]
So the red one is validation from backend. That exists for all of them. The tool tip is just an extra validation from the front end which at the moment only exists for events. Do you want me to get rid of front end validation for event or add it in to all the other components for consistency?

**Comment by ctrance** [comment]
@shaun965 - To make it consistent, please add the red message validation from the back end.

**Comment by ctrance** [comment]
@joshuaselsky and @shaun965 - I still don't see the red message on Events page unlike other pages. There's tool tip error message, are we okay with that? If yes, I can close this...

**Comment by shaun965** [comment]
I got the changes in locally, we are in the process of making my pull request possible because I need to do a few extra things with the password validation. Just to make sure, you want me to remove all the tooltip message correct? The red error is already working for all of the components. The tool tip is just an extra check from the front end that is implemented for events prior to me working on this.

**Comment by ctrance** [comment]
I'd like to defer the removal of the tool tip validation message to the team. I just think it would be nice to make everything consistent. On other pages it's just the red text error message, no tool tip.

**Comment by joshuaselsky** [comment]
We voted to make the design consistent (yay) and we won't show the tool tip.

**Comment by ctrance** [comment]
fixed
