### ISSUE TITLE
Need design to indicate the badge/award is showcased on their profile

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#277]
Please create an icon or marker that will indicate the badge/award is showcased on the profile page. Maybe a check mark?
![capture](https://cloud.githubusercontent.com/assets/1034174/10946055/1194b790-82d5-11e5-99c0-9e24839426e3.PNG)

**Comment by laurencullen** [comment]
@ctrance  Yes, I can do this. So that I know size and color, where is the icon/marker going to display on this screen? For example, in blue box? If so, where specifically in blue box? Thanks!

**Comment by ctrance** [comment]
@laurencullen - As we've discussed offline, a check mark right next to the badge/award image. Thanks!

**Comment by laurencullen** [comment]
@ctrance @krozett @rrocchio Here is a check mark that goes right next to badge/award image. Also, I made a design for the page so that we could see where it goes. Please let me know if you need anything else. Thanks!

![ucnext badge checkmark-page](https://cloud.githubusercontent.com/assets/13141571/10948773/29905f2a-82e4-11e5-9dfc-fd8d55cc124b.jpg)

![badge checkmark](https://cloud.githubusercontent.com/assets/13141571/10948775/2e5eafd4-82e4-11e5-9030-f8e9c7400d10.png)

**Comment by krozett** [comment]
Self-assigning so I can implement this.

**Comment by laurencullen** [comment]
@krozett the badges look much improved, thank you for the changes!

For this profile page with badges, is it possible to make some changes so that it looks like proof above? For example Badges and Awards header centered and not all caps. Name centered and not all caps. First two lines of badge description smaller font with less space between lines (in the comp, the font is 10pt). After the first two lines of the description text have a "..." so that the user would know there is more.

Also, we had discussed adding the green checkmark attached above for badges that the user already has. Please let us know if this is possible to do.

**Comment by laurencullen** [comment]
@krozett After just speaking with Josh, I realize that the above changes might be made already but not live yet. When I saw this was assigned to me, I thought you were wanting for me to take a look at the live site. So, please let me know if there's anything you need with it :)

**Comment by krozett** [comment]
@laurencullen So what I mean is that I think it's a good design for the "show all badges / awards" page that you get by clicking on a different user's profile. I just need to implement it.

However, I think it won't work for the edit profile version of the page. Right now the design of #119 has the badges show up when editing your own profile. Now that's not in place, but that was the design I was expecting to implement. Has this changed?

**Comment by laurencullen** [comment]
@krozett Great that design will work for looking at all badges on a different user's profile :)

For the edit profile version of the page, the design of #119 is what I'm also expecting to implement. When the user clicks see all badges (top right corner of design), where does that go? I thought it would be the same page as show all badges/awards but for the user's personal group of badges and awards (with the remove button present).

**Comment by krozett** [comment]
@laurencullen Yes, I forgot about that link, but it would go to the same page you have designed above. Isn't that what the page is showing, the user's personal group of badges/awards rather than all badges/awards in the system?

**Comment by laurencullen** [comment]
@krozett yes, that is my understanding as well.

**Comment by ctrance** [comment]
@krozett and @joshuaselsky - Check mark icon shows for hidden badges/awards in the Profile page. The said icon should only show for showcased badges/awards.

**Comment by krozett** [comment]
I was confused about the requirements of this. Just to make sure, I am only displaying checkmarks when viewing a particular user's badges (could be current user, or a different one). Not on the main badges page that shows all the badges in the system, right?

And I'm showing the checkmark if the relevant user has the badge showcased, correct? For example, if I'm viewing Josh's badges, a checkmark shows for any badge he has showcased.

**Comment by ctrance** [comment]
@krozett - Yes, you're only going to show the checkmark icon if the badge/award is showcased on the user's profile page. If the badge/award is hidden on the user's profile page then don't show the checkmark icon.

**Comment by krozett** [comment]
@ctrance - Great! This code has been merged so it should be testable now. :)

**Comment by ctrance** [comment]
fixed
