### ISSUE TITLE
badges / awards on profile page are too small

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#280]
Please make them large enough so they are legible.

**Comment by krozett** [comment]
I was mistaken that we were saving the full-quality badge images. I've made it so that the original image is always saved, and things can simply be sized down when needed. I did make the default "thumbnail" size larger, 120x120 instead of 75x75, so the text should be visible now. We will always display thumbnail size, unless you click on an individual badge detail page, then we blow it up to 100% of the screen width.

**Comment by joshuaselsky** [comment]
@krozett I just uploaded a full size badge image because I noticed they were missing on the staging box.  Here's what it looks like on the [badges/awards page](https://staging.ucnext.org/badges) and on the (badge detail page)[https://staging.ucnext.org/badges/1].

Let me know if you'd like me to open a new issue.

**Comment by krozett** [comment]
That's okay, @joshuaselsky, I'll be taking care of the final look in #262. I understand it looks weird right now. How is the size? The tiny text under "UCSSC" still isn't visible in the thumbnail version, but I'm trying to find a nice medium ground for badge sizes that won't blow up on mobile sizes. For that particular one, you have to make at least 180x120 before you can read the "in a cloud of our own" part.

**Comment by joshuaselsky** [comment]
I'd say the size should be appropriate for readability like you are suggesting. I can upload the rest of the images if that helps.

**Comment by krozett** [comment]
That would be great, thanks @joshuaselsky. But it has to wait until the code is deployed to production.
