### ISSUE TITLE
Awarding "...Sautter Award" adds incorrect points to the Engagement Meter

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#296]
#123 
* App only adds 25 points for "8) Awarding a GOLD Sautter Award for your campus = 50 points for you and your campus"
* App only adds 10 pts for "9) Awarding a SILVER Sautter Award for your campus = 25 points for you and your campus"

**Comment by krozett** [comment]
I see. The badge point values have been changed in the database to 25/10 points. Let's discuss and figure out which values are correct. Ideally we should just pull the current value from the database and display that on this page, but our badge infrastructure doesn't allow this right now (because we have many copies of the Sautter awards). That should probably be discussed as well.

**Comment by joshuaselsky** [comment]
The fix for this is to update the points in the description about points.

**Comment by ctrance** [comment]
fixed
