### ISSUE TITLE
update headers on home page

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#310]
The "trending" sort order is confusing without a little explanatory UI. Can something like the following be added? 

* Rename PROJECTS to TRENDING PROJECTS (with the words on two lines)
* Rename IDEAS to TRENDING IDEAS (with the words on two lines)
* Add the rank on the left-hand side.
* Add a "Votes" header above column that contains the bubbles with number of votes.
* Add alt text over the word "trending" with our definition. (to be emailed)

**Comment by laurencullen** [comment]
@joshuaselsky The heading on projects and ideas here was previously discussed. On the projects and ideas page we have Top Five Projects/Ideas by Vote. @rrocchio what would you like to do for the wording on the home page?

If we need to add description text for the bubbles, I think that the word "VOTES" in very small print under the number in the bubble would look best. Or, maybe we could do a hover popup that says number of votes? When the user is logged in, we could add the +1 button so that it is more obvious what the number goes to and we might not need any extra text at all...

Maybe items to discuss at this week's meeting?

**Comment by joshuaselsky** [comment]
Yes, definitely. The heading on the home page came up in the steering committee meeting today. It is potentially confusing because the order is not a straight-forward sort; it actually is trending order.

**Comment by joshuaselsky** [comment]
We discussed this in our meeting and updated the comment in the first issue with the actual to-dos.

**Comment by krozett** [comment]
Addressed in PR #340

**Comment by ctrance** [comment]
@krozett - The Rank and Votes header looks off on iphone 6 view, it's indented (see below) 
![img_9440 1](https://cloud.githubusercontent.com/assets/1034174/11943943/b94d42d6-a7f6-11e5-9d7a-533206bbe907.PNG)

**Comment by ctrance** [comment]
fixed
