### ISSUE TITLE
email is not sent when joining a group

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#321]
An email containing the Group's badge should be sent to the new group member.

**Comment by krozett** [comment]
It's working for me now. Please re-test and close if it works. :)

**Comment by ctrance** [comment]
@joshuaselsky and @krozett - If a group has a badge, the app is sending email about the award/badge recipient. If a group doesn't have a badge and the user joined it, the app doesn't generate new group member email. 

Is that the expected behavior? Or regardless if the group has a badge or not the app should send new group member email?

**Comment by krozett** [comment]
@ctrance There is only an email if the group has a badge. No email goes out if the group has no badge.

**Comment by ctrance** [comment]
I'm closing this then :)
