### ISSUE TITLE
"Would Participate" should not trigger "Good Idea"

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#327]
When I click "Would Participate", "Good Idea" button changed to "Withdraw Support" as if I clicked it too. If I click "Withdraw Participation" button, "Withdraw Support" button lingers. Per @joshuaselsky - "Would Participate" and "Good Idea" should be independent from each other.

**Comment by krozett** [comment]
I think we should have a discussion about this, because we've always had "would participate" also cover "good idea". In other words, "would participate" means "it's a good idea AND I will participate".

**Comment by ctrance** [comment]
@krozett - Actually it makes sense, if I participate that means I like the idea. I just want to clarify if that's the expected behavior. The question now is if I withdraw my participation, should the app auto-withdraw the support too?

**Comment by krozett** [comment]
@ctrance That's a good question. Personally I feel that withdrawing participation should not withdraw support. If you are in the "would participate" state, you see 2 buttons: "withdraw participation" and "withdraw support". Since a user can already withdraw their support completely with the second button, the first button would imply that it would only withdraw participation without withdrawing support.

**Comment by ctrance** [comment]
I guess we can assume that if they don't want to participate anymore doesn't mean they don't want to support the idea/project anymore. Unlike participating automatically means you like the idea, that's why you participated in the first place :). User would just do a second click to withdraw the support. @joshuaselsky - What do you think, should I close this?

**Comment by joshuaselsky** [comment]
I agree and I think we partially had this discussion last week. It is nice to offer the flexibility of saying "Even though I can no longer participate, I still like this idea / project."
