### ISSUE TITLE
Got error page when giving other person award/badge

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#337]
I was logged in as (ctrance@ucla.edu - admin), when I give award/badge to other person (ctrance@oit.ucla.edu) the app is throwing error page.

**Comment by joshuaselsky** [comment]
Please see the last comment in #257 for details.

**Comment by krozett** [comment]
There was some bad data in the database that was causing user ctrance@oit.ucla.edu to have invalid badge data. (https://staging.ucnext.org/users/26/badges) It wasn't due to the badge giving itself, but rather the badge giving redirected to this page, which had errors.

I cleaned out the bad data. Then I managed to find one potential cause of the invalid data, but that only explains one of the two error-prone lines I found in the logs.

@ctrance Could you try testing again? Let's see if it's possible to reproduce the bad data.

**Comment by ctrance** [comment]
I cannot reproduce this error anymore. I even tried removing a badge and awarding it again but no errors...
