### ISSUE TITLE
Email filter for staging

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#377]
On staging, there should be a filter that only sends emails to a whitelisted group of recipients. This is to avoid the issue described here: #366.

**Comment by joshuaselsky** [comment]
@ctrance the way to test this is that on staging only the users in this [file](https://github.com/universityofcalifornia/NeXt/blob/master/config/whitelist_email.yml) should receive emails.

**Comment by ctrance** [comment]
@joshuaselsky - I voted on Logan Franken's project for participation but I did not receive email. Is that because I'm not the creator of the project? Then the only way to verify is to check the email record if it's sent to Logan Franken. I don't have access to the main email record, can you please check?

**Comment by joshuaselsky** [comment]
@ctrance This [project](https://staging.ucnext.org/projects/19) belongs to my non-OIT work email which isn't in the list.  If you vote on it, I will verify that I did not receive an email. How is that?

**Comment by ctrance** [comment]
@joshuaselsky - I just voted on your project that belongs to your non-OIT work email. Can you please check? Thanks!

**Comment by joshuaselsky** [comment]
Checked and I didn't receive an email.

**Comment by ctrance** [comment]
Thanks @joshuaselsky - I'll close this :)
