### ISSUE TITLE
email redesign

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#414]
Our existing set of emails needs some serious design input. 

The emails should use a template with a standard UC Next header and footer. 

Here are the current emails sent by the system:
* weekly activity summary
* user has been invited to an event
* user has been made a founder of an idea (transfer founder)
* user has been made a founder of a project (transfer founder)
* user has received a badge
* password reset
* a user has participated in your idea
* a user has participated in your project

**Comment by laurencullen** [comment]
@joshuaselsky @shaun965 Please let me know if this is the kind of thing you were thinking of...

Also, in terms of the footer text, it should be the same on all emails. We could do a message about unsubscribing or this proof includes a simplified version with subscription preferences | unsubscribe. Please let me know any preferences on the text.

![email template-01](https://cloud.githubusercontent.com/assets/13141571/13539750/2529acf2-e207-11e5-8a99-afc24977dc98.jpg)

**Comment by shaun965** [comment]
@laurencullen  looks nice! can you upload the assets in this and I will try to fit them in?

**Comment by laurencullen** [comment]
@shaun965 here are the images. provided both the wave with text and without so that you can decide which works better. the rest would be styles. colors all match ones in website: #121212, #9C5500, and #0455A4.

Please let me know if you need anything else.

![logo](https://cloud.githubusercontent.com/assets/13141571/14091566/d3a67962-f4f5-11e5-994f-518ec11865e2.png)
![wave](https://cloud.githubusercontent.com/assets/13141571/14091567/d3a8949a-f4f5-11e5-9bd5-012bf009780f.png)
![waveandtext](https://cloud.githubusercontent.com/assets/13141571/14091568/d3ae199c-f4f5-11e5-85dc-43e1b6572dc7.png)

**Comment by ctrance** [comment]
@shaun965 @joshuaselsky - Cannot fully test this, staging did not submit email and some events below throw error:
1. Transfer idea founder
2. Receiving badge
3. Password reset
4. Participate in an idea

Also, when does "weekly activity summary" email get sent?

**Comment by ctrance** [comment]
@joshuaselsky @shaun965 - The badge email does not have the footer, see below.
![capture](https://cloud.githubusercontent.com/assets/1034174/14215682/4e74cecc-f7f9-11e5-8165-6b997d156ff1.PNG)

**Comment by ctrance** [comment]
@shaun965 @joshuaselsky - The weekly activity summary is missing the header/footer, see below:
![capture](https://cloud.githubusercontent.com/assets/1034174/14264336/54e50e52-fa74-11e5-90ee-9fdddd9372d1.PNG)

**Comment by ctrance** [comment]
@shaun965 @joshuaselsky - Badge email has footer now. Please fix weekly activity summary too.

**Comment by ctrance** [comment]
Weekly activity summary email now shows UC Next header and footer.
