### ISSUE TITLE
Where is the comps for decreased width of Home page?

### ISSUE THREAD

**Issue by ctrance** [universityofcalifornia/NeXt#439]
@laurencullen @joshuaselsky #384 - "Please decrease the width of the two columns because it needs a little more space (as seen in comps)." - I don't see the comps to compare with, please provide so I can test.

**Comment by laurencullen** [comment]
@ctrance Here is a comp of the homepage. Since this one from Oct, I believe we made the buttons in all caps to be consistent throughout, but I think that the rest is up-to-date.
Please let me know if you need anything else or have any questions :)
![ucnext_homepage](https://cloud.githubusercontent.com/assets/13141571/14896360/3548b640-0d32-11e6-85f9-54c0880674eb.png)

**Comment by ctrance** [comment]
Thanks @laurencullen!
