### ISSUE TITLE
[discuss] should we combine the back-end on the ideas and projects? (structure is very similar)

### ISSUE THREAD

**Issue by jurowski** [universityofcalifornia/NeXt#59]
Chris H. had asked me yesterday after looking @ the models for Idea and Project whether they should be combined into one model, with a boolean flag to indicate if it was an idea or project.

Thoughts on that?

**Comment by ctmcintyre** [comment]
Since our current idea is that projects would be jettisoned from the 
platform (we won't be providing project support), having a boolean for 
idea/project seems fine.  I look at it as stages of an idea, caterpillar 
to butterfly style (hairbrain idea->gaining traction->resourced->becomes 
a project->fails or delivers).



> Sandon Jurowski <mailto:notifications@github.com>
> May 8, 2015 at 7:15 AM
>
> Chris H. had asked me yesterday after looking @ the models for Idea 
> and Project whether they should be combined into one model, with a 
> boolean flag to indicate if it was an idea or project.
>
> Thoughts on that?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/universityofcalifornia/NeXt/issues/59>.
>

-- 
Charles McIntyre
Manager, Infrastructure & Operations

Application & Project Management
Information Technology Services

office: 831/459-5746

**Comment by rrocchio** [comment]
Charles, we actually disagree, and feel that they should be kept separate.
We discussed this at the last meeting, and today as well, we don't agree that they should share a backend since they can have a many to many or an one to many relationship...
Ideas - are different in nature, and as far as supporting project collaboration - I think that the platform should do this

**Comment by ctmcintyre** [comment]
I concur with you Rose.  I didn't think of the many to many relationships.  I'm OK with having separate backends for ideas and projects.

**Comment by pmeads** [comment]
Closing. Ideas and Projects will remain separate.
