### ISSUE TITLE
[Badges] We will do a second kind of Badges for Awards

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#96]
Thinking we will need 3 tables - one for the Awards themselves, and then one to record the people who gave them and a third to store who can edit the awards

One that stores the Award Badges infos

THE TABLE ABOUT THE AWARDS should have these fields:

TABLE NAME:  TBL_AWARD_BADGES

Award_Badge_id
Name of Award Badge
Description of Award Badge
Date Awarded
Website
Type of Award
Badge Image
Badge Image date
Group or Individual
Number of Awards Given
Award Owner
Award Given By 
create date
Created by
Update date
Updated by

A Second table should store the info about who gets it

TBL_AWARD_BADGES_GIVEN

Award_Badge_id
UC_Loc_id
EPPN
Date_Awarded
Create_date
Created_by
Update_date
Updated_by

A Third table should store who can edit the awards

TBL_AWARD_BADGE_EDITORS

Award_Badge_id
NeXt_User_id
EPPN
Create_date
Created_by
Update_date
Updated_by

**Comment by rrocchio** [comment]
@krozett  - there is a specific Award to be given
called the Larry Sautter award   - check out this website - http://cnc.ucr.edu/sautter/ - it will give you a good idea of this type of award and we can figure out what else we might want to store regarding these awards!

**Comment by rrocchio** [comment]
@ctmcintyre  - do you have anything to add here?

**Comment by krozett** [comment]
@rrocchio - a few questions:
1. What is UC_Loc_id?
2. EPPN is a Shibboleth thing, right? Do we need to record this? It seems to me that NeXt user ids should suffice for both award editors and recipients.
3. What is "group or individual" in the first table?

I think we should resist the temptation to put as much info as possible in the tables, because a lot of it is going to be dependent on the award itself. Users who want to see all the award details should go to the award's website which we will link to. In my opinion we should keep the info on NeXt fairly limited.

**Comment by krozett** [comment]
@rrocchio - further thoughts... do we even need to separate badges and awards this much? I think that from the point of view of NeXt, they are images attached to some extra information. We don't have a system in place to grant badges yet. Giving a competency-based badge and an award badge are pretty much the same thing, aren't they?

**Comment by krozett** [comment]
After going over the fields closely again, I realized that most of these fields can actually be derived in other places. For example, 'date awarded' would simply be the created_at time in the UserBadge model. Number of awards given could be calculated by doing simple SQL counts. The only field I had to add was website URL. I ended up going with STI (single table inheritance) so that Awards have their own class but are otherwise the same as badges. Once we actually have some logic for awards vs. badges we can put that in the appropriate class.

**Comment by ctrance** [comment]
@krozett - Do I have to be admin to give awards? Please add test instructions for this task.

**Comment by krozett** [comment]
@ctrance There are 2 ways to give awards:
* Create an award, which requires admin privileges.
* Have the owner of an existing award add you to the "badge givers" list, which can be done on the Badge Edit page.

The first option is probably the best, we'll try to get you admin access ASAP.

**Comment by ctrance** [comment]
@krozett - Thanks! I'll proceed testing this once I got admin access.

**Comment by ctrance** [comment]
Awards/Badges are working good now.
